name: Latest blog post workflow
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

# Fixes the Node warning
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in zura.id.vn posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://zura.id.vn/rss.xml"
